### PR TITLE
fix `getUserData` for apps that aren't bots

### LINKED ISSUE #56: Fails when committer is an app (not a user)
This line fails:

https://github.com/embroider-build/github-changelog/blob/932b1c78ca2c2a8487d89fc3c86dfa7436412680/src/changelog.ts#L137

When the `login` is not a user, but an app:

```
{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}
```

For example, I traced it down to the login: `Copilot`, but the there is no user named `Copilot`, instead it is this app: https://github.com/apps/copilot-swe-agent

---

I can take a look later and provide a PR.

### PR DESCRIPTION
**Pull request by gossi**
Fixes #56 - and in turn fixes a broken `release-plan`

### CODE REVIEW

File: src/github-api.ts [hunk 1]
```diff
@@ -54,9 +61,23 @@ export default class GithubAPI {
...
+
+    if (userInfo.html_url && userInfo.html_url.includes("/apps/")) {
+      path = "apps";
+      login = userInfo.html_url.split("/").pop() as string;
+    }
     const prefix = process.env.GITHUB_API_URL || `https://api.${this.github}`;
-    return this._fetch(`${prefix}/users/${login}`);
+    const data = await this._fetch(`${prefix}/${path}/${login}`);
+
+    if (login === "Copilot") {
```
Comment (kategengler) [inline src/github-api.ts]: I think this should be at a different level, maybe where we ignore committers?

Comment (kategengler) [reply src/github-api.ts]: I think the sanitization should go at the same level as the ignoring, is what I mean

File: src/github-api.ts [hunk 2]
```diff
@@ -54,9 +61,18 @@ export default class GithubAPI {
     return this._fetch(`${prefix}/repos/${repo}/issues/${issue}`);
   }
 
-  public async getUserData(login: string): Promise<GitHubUserResponse> {
+  public async getUserData(userInfo: Pick<GithubUserInfo, "login" | "html_url">): Promise<GitHubContributor> {
+    let login = userInfo.login;
+    let path = "users";
+
+    // github API itself does not tell if contributor is an app. Best guess was to
+    // check the `html_url` for the `/apps/` segment
```
[the remark this answers is not in the document]
Comment (wagenet) [reply src/github-api.ts]: Ah, I see, apps are a sub-type of Bot.

**Comment by gossi** [comment]
@wagenet which committers list? I think I touched all occurences I could find

**Comment by wagenet** [comment]
See the list at the end. However, this was generated from a patch based on this PR so maybe I missed something on my end.

image

**Review by mansona — APPROVED** [review]
